# Generated by Django 4.1.3 on 2022-11-17 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_report_medcare"),
    ]

    operations = [
        migrations.RemoveField(model_name="report", name="doc_id",),
        migrations.AddField(
            model_name="report",
            name="imag",
            field=models.ImageField(default="NULL", upload_to="static/img/report"),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Documents",),
    ]
